# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 937977bf7222a6ab5379efede75accf438e84e3cf36a70a3b5844fba2b42b91dd9782017aff38c2a0fb7d7861a34f58c4d407a1db4f72fbaedd989da400b3e4a

test:
  secret_key_base: e45917b54fa9a459a972563793e7fc1ef557fce5e1700524d50d417cc4621c1991c9465f689adb94ec42969d23e9f61fb5d843599016c713bd07bbf48eabb050

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
